name: 'Recognition'
description: 'Allocate labels depends on changed files'
inputs:
  matrix:
    description: 'Entities to be recognized under label source, used as output field in matrix. JSON string.'
    required: false
  token:
    description: 'GitHub token'
    required: true
  source:
    description: 'Label source filename'
    required: true
outputs:
  matrix:
    description: 'Matrix based on label entities in JSON format'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: target
  color: gray-dark
